sonar.projectKey=infobyte_ekofiesta
sonar.organization=infobyte

# Metadata
sonar.projectName=ekofiesta
sonar.projectVersion=1.0
sonar.sourceEncoding=UTF-8

# Source code
sonar.sources=.
sonar.exclusions=node_modules/**,dist/**,build/**,.git/**,tests/**,**/*.test.js,**/*.spec.js

# JavaScript/TypeScript specific
sonar.javascript.lcov.reportPaths=coverage/lcov.info

# Quality gate
sonar.qualitygate.wait=false
