sonar.projectKey=faradaysec_ekofiesta
sonar.organization=faradaysec

# Metadata
sonar.projectName=ekofiesta
sonar.projectVersion=1.0
sonar.sourceEncoding=UTF-8

# Source code
sonar.sources=.
sonar.exclusions=node_modules/**,dist/**,build/**,.git/**,tests/**,**/*.test.js,**/*.spec.js

# Quality gate
sonar.qualitygate.wait=false
