export interface AgendaItem {
  id: string
  day: string       // 'day1' | 'day2' | 'day3'
  date: string      // 'YYYY-MM-DD'
  time_start: string
  time_end: string
  title: string
  speaker: string
  track: 'main' | 'workshop' | 'village' | 'ctf' | 'panel'
  room: string
  language: 'es' | 'en'
  description?: string
}

export interface AgendaDay {
  id: string
  date: string
  label_es: string
  label_en: string
  label_pt: string
  items: AgendaItem[]
}

// Mocked from https://ekoparty.org/agenda-2026/
// Replace with live data fetched via the MCP tool `fetch_eko_agenda`
export const agenda: AgendaDay[] = [
  {
    id: 'day1',
    date: '2026-10-07',
    label_es: 'Día 1 · Miércoles 7',
    label_en: 'Day 1 · Wednesday 7',
    label_pt: 'Dia 1 · Quarta 7',
    items: [
      {
        id: 'a1-1',
        day: 'day1',
        date: '2026-10-07',
        time_start: '09:00',
        time_end: '09:45',
        title: 'Apertura Oficial EkoParty 2026',
        speaker: 'Federico Kirschbaum, Andrés Riancho',
        track: 'main',
        room: 'Auditorio Principal',
        language: 'es',
        description: 'Bienvenida oficial a la edición 2026. Agenda, highlights y anuncios del equipo organizador.',
      },
      {
        id: 'a1-2',
        day: 'day1',
        date: '2026-10-07',
        time_start: '10:00',
        time_end: '11:00',
        title: 'The Future of Offensive AI: When Your Attacker Has an LLM',
        speaker: 'Dr. Valentina Ríos',
        track: 'main',
        room: 'Auditorio Principal',
        language: 'en',
        description: 'How large language models are changing the attacker playbook — from phishing automation to autonomous exploit generation.',
      },
      {
        id: 'a1-3',
        day: 'day1',
        date: '2026-10-07',
        time_start: '11:15',
        time_end: '12:15',
        title: 'Explotación Avanzada de Allocators en Linux Moderno',
        speaker: 'Gabriel Campana',
        track: 'main',
        room: 'Auditorio Principal',
        language: 'es',
        description: 'Técnicas de heap exploitation en glibc 2.38+: House of Einherjar, tcache poisoning y nuevas mitigaciones.',
      },
      {
        id: 'a1-4',
        day: 'day1',
        date: '2026-10-07',
        time_start: '12:30',
        time_end: '14:00',
        title: 'Almuerzo',
        speaker: '',
        track: 'village',
        room: 'Área de Villages',
        language: 'es',
      },
      {
        id: 'a1-5',
        day: 'day1',
        date: '2026-10-07',
        time_start: '14:00',
        time_end: '15:00',
        title: 'Supply Chain Attacks in 2026: Lessons from the XZ Backdoor',
        speaker: 'Andrés Torres',
        track: 'main',
        room: 'Auditorio Principal',
        language: 'en',
        description: 'Post-mortem and generalization of the XZ backdoor attack. How to detect and prevent supply chain compromises at scale.',
      },
      {
        id: 'a1-6',
        day: 'day1',
        date: '2026-10-07',
        time_start: '14:00',
        time_end: '18:00',
        title: 'Hardware Hacking Village',
        speaker: 'Hardware Village Crew',
        track: 'village',
        room: 'Village Hall A',
        language: 'es',
        description: 'Teardowns, JTAG, UART, fault injection y más. Traé hardware para analizar.',
      },
      {
        id: 'a1-7',
        day: 'day1',
        date: '2026-10-07',
        time_start: '15:15',
        time_end: '16:15',
        title: 'Reversing Firmware con Ghidra y Claude: Un Flujo Moderno',
        speaker: 'Matías Hernández',
        track: 'main',
        room: 'Auditorio Principal',
        language: 'es',
        description: 'Cómo usar LLMs como asistentes de reverse engineering sin filtrar código propietario.',
      },
      {
        id: 'a1-8',
        day: 'day1',
        date: '2026-10-07',
        time_start: '16:30',
        time_end: '18:00',
        title: 'Workshop: Introducción al Fuzzing con AFL++',
        speaker: 'Paula Fernández, Diego Soria',
        track: 'workshop',
        room: 'Sala Taller 1',
        language: 'es',
        description: 'Hands-on: configurá tu primer harness, entendé coverage-guided fuzzing, analiza crashes. Traé laptop.',
      },
      {
        id: 'a1-9',
        day: 'day1',
        date: '2026-10-07',
        time_start: '18:00',
        time_end: '18:45',
        title: 'Lightning Talks',
        speaker: 'Varios speakers',
        track: 'main',
        room: 'Auditorio Principal',
        language: 'es',
        description: '5 charlas de 10 minutos cada una. Sorpresas garantizadas.',
      },
    ],
  },
  {
    id: 'day2',
    date: '2026-10-08',
    label_es: 'Día 2 · Jueves 8',
    label_en: 'Day 2 · Thursday 8',
    label_pt: 'Dia 2 · Quinta 8',
    items: [
      {
        id: 'a2-1',
        day: 'day2',
        date: '2026-10-08',
        time_start: '09:00',
        time_end: '10:00',
        title: 'Browser Security in 2026: MV3 Exploitation and Chrome Internals',
        speaker: 'Camille Desnoyers',
        track: 'main',
        room: 'Auditorio Principal',
        language: 'en',
        description: 'Deep dive into Manifest V3 bypass techniques, renderer exploitation, and Chrome\'s site isolation in 2026.',
      },
      {
        id: 'a2-2',
        day: 'day2',
        date: '2026-10-08',
        time_start: '10:15',
        time_end: '11:15',
        title: 'Misconfiguraciones Cloud a Escala: AWS, GCP y Azure en el Crosshair',
        speaker: 'Roberto Díaz',
        track: 'main',
        room: 'Auditorio Principal',
        language: 'es',
        description: 'Análisis de miles de cuentas cloud mal configuradas. Patrones, herramientas y cómo defenderse.',
      },
      {
        id: 'a2-3',
        day: 'day2',
        date: '2026-10-08',
        time_start: '11:30',
        time_end: '12:30',
        title: 'ICS/SCADA Attacks on Critical Infrastructure',
        speaker: 'Marcelo Rivero, Ana Gutiérrez',
        track: 'main',
        room: 'Auditorio Principal',
        language: 'en',
        description: 'Real case studies from industrial network attacks in LATAM. Modbus, DNP3, and Profinet weaponization.',
      },
      {
        id: 'a2-4',
        day: 'day2',
        date: '2026-10-08',
        time_start: '12:30',
        time_end: '14:00',
        title: 'Almuerzo + Villages',
        speaker: '',
        track: 'village',
        room: 'Área de Villages',
        language: 'es',
      },
      {
        id: 'a2-5',
        day: 'day2',
        date: '2026-10-08',
        time_start: '14:00',
        time_end: '18:00',
        title: 'CTF EkoParty 2026',
        speaker: 'EkoParty CTF Team',
        track: 'ctf',
        room: 'CTF Arena',
        language: 'es',
        description: 'El CTF principal de EkoParty. Categorías: pwn, web, crypto, reversing, misc. Premios en efectivo.',
      },
      {
        id: 'a2-6',
        day: 'day2',
        date: '2026-10-08',
        time_start: '14:00',
        time_end: '15:00',
        title: 'Mobile Forensics: Extracción y Análisis Avanzado en iOS y Android',
        speaker: 'Sergio Álvarez',
        track: 'main',
        room: 'Auditorio Principal',
        language: 'es',
        description: 'De la extracción lógica al análisis forense avanzado. Cómo manejar cifrado y particiones dañadas.',
      },
      {
        id: 'a2-7',
        day: 'day2',
        date: '2026-10-08',
        time_start: '15:15',
        time_end: '16:15',
        title: 'Zero-Day Research: From Discovery to Responsible Disclosure',
        speaker: 'Team Nuit de Sécurité',
        track: 'main',
        room: 'Auditorio Principal',
        language: 'en',
        description: 'The full lifecycle of zero-day research: finding bugs, writing PoCs, coordinating disclosure, and navigating bug bounty programs.',
      },
      {
        id: 'a2-8',
        day: 'day2',
        date: '2026-10-08',
        time_start: '16:30',
        time_end: '18:00',
        title: 'Panel: Ética en Seguridad Ofensiva — ¿Dónde Está el Límite?',
        speaker: 'Federico Kirschbaum, Paula Fernández, Roberto Díaz, Ana Gutiérrez',
        track: 'panel',
        room: 'Auditorio Principal',
        language: 'es',
        description: 'Debate abierto sobre ética, legalidad y responsabilidad en el trabajo de pentest y research.',
      },
      {
        id: 'a2-9',
        day: 'day2',
        date: '2026-10-08',
        time_start: '16:30',
        time_end: '18:00',
        title: 'Workshop: Web Hacking Moderno — XSS, SSRF, y HTTP Request Smuggling',
        speaker: 'Diego Soria',
        track: 'workshop',
        room: 'Sala Taller 1',
        language: 'es',
        description: 'Explotación práctica de vulnerabilidades web en aplicaciones modernas. Casos reales de bug bounty.',
      },
    ],
  },
  {
    id: 'day3',
    date: '2026-10-09',
    label_es: 'Día 3 · Viernes 9',
    label_en: 'Day 3 · Friday 9',
    label_pt: 'Dia 3 · Sexta 9',
    items: [
      {
        id: 'a3-1',
        day: 'day3',
        date: '2026-10-09',
        time_start: '09:00',
        time_end: '10:00',
        title: 'Reverse Engineering con Asistencia de IA: Workflows Reales',
        speaker: 'Lucas Pinheiro',
        track: 'main',
        room: 'Auditorio Principal',
        language: 'es',
        description: 'Casos de uso reales de IA en RE: deobfuscation, naming, y análisis de código malicioso.',
      },
      {
        id: 'a3-2',
        day: 'day3',
        date: '2026-10-09',
        time_start: '10:15',
        time_end: '11:15',
        title: 'Kubernetes Cluster Takeover: From Pod Escape to Cloud Root',
        speaker: 'Natalia Espinoza',
        track: 'main',
        room: 'Auditorio Principal',
        language: 'en',
        description: 'Complete attack path from a vulnerable container to full cloud account compromise. Live demo included.',
      },
      {
        id: 'a3-3',
        day: 'day3',
        date: '2026-10-09',
        time_start: '11:30',
        time_end: '12:30',
        title: 'El Arte del Social Engineering en 2026',
        speaker: 'Carlos Valiente',
        track: 'main',
        room: 'Auditorio Principal',
        language: 'es',
        description: 'Vishing, smishing y deepfakes como vectores de ataque. Casos de red teaming real en Argentina.',
      },
      {
        id: 'a3-4',
        day: 'day3',
        date: '2026-10-09',
        time_start: '12:30',
        time_end: '14:00',
        title: 'Almuerzo + CTF Finals',
        speaker: '',
        track: 'ctf',
        room: 'CTF Arena',
        language: 'es',
      },
      {
        id: 'a3-5',
        day: 'day3',
        date: '2026-10-09',
        time_start: '14:00',
        time_end: '16:00',
        title: 'Workshop: Análisis de Malware con CAPE Sandbox',
        speaker: 'Equipo ESET LATAM',
        track: 'workshop',
        room: 'Sala Taller 1',
        language: 'es',
        description: 'Análisis dinámico de malware moderno usando CAPE Sandbox. Casos de ransomware y spyware de LATAM.',
      },
      {
        id: 'a3-6',
        day: 'day3',
        date: '2026-10-09',
        time_start: '14:00',
        time_end: '15:30',
        title: 'Threat Intelligence for LATAM: Building a Regional Sharing Network',
        speaker: 'Valentina Ríos, Roberto Díaz',
        track: 'main',
        room: 'Auditorio Principal',
        language: 'en',
        description: 'How to build effective ISAC-style threat sharing in Latin America. Tools, trust models and case studies.',
      },
      {
        id: 'a3-7',
        day: 'day3',
        date: '2026-10-09',
        time_start: '15:45',
        time_end: '16:30',
        title: 'Premiación CTF EkoParty 2026',
        speaker: 'EkoParty CTF Team',
        track: 'ctf',
        room: 'Auditorio Principal',
        language: 'es',
        description: 'Entrega de premios a los ganadores del CTF. Los 3 primeros equipos presentan sus soluciones.',
      },
      {
        id: 'a3-8',
        day: 'day3',
        date: '2026-10-09',
        time_start: '16:45',
        time_end: '18:00',
        title: 'Keynote de Cierre: Seguridad Ofensiva y el Futuro de la Defensa',
        speaker: 'Andrés Riancho',
        track: 'main',
        room: 'Auditorio Principal',
        language: 'es',
        description: 'Reflexiones sobre el estado del arte, los desafíos del futuro y el rol de la comunidad Argentina en la seguridad global.',
      },
    ],
  },
]
